version: "3.9"

services:
  backend:
    container_name: tianyu-website-backend
    image: ghcr.io/TianYu-00/tianyu-website-backend:latest
    ports:
      - "34443:9090"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PGDATABASE=${PGDATABASE}
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - tianyu-website-network

  frontend:
    container_name: tianyu-website-frontend
    image: ghcr.io/TianYu-00/tianyu-website-frontend:latest
    ports:
      - "34442:80"
    restart: unless-stopped
    networks:
      - tianyu-website-network

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=30
      - GHCR_USERNAME=${GHCR_USERNAME}
      - GHCR_TOKEN=${GHCR_TOKEN}
    networks:
      - tianyu-website-network

networks:
  tianyu-website-network:
    driver: bridge
